### ISSUE TITLE
[Bug] Getting `UniqueConstraintError` when using `Schema.upsert`

### ISSUE THREAD

**Issue by benbaessler** [ponder-sh/ponder#1047]
In my deployment logs on Railway I'm getting this error when starting the application. 
```
Failed 'User.upsert' database method with non-retryable error: UNIQUE constraint failed: User.id
UniqueConstraintError: UNIQUE constraint failed: User.id
```

This is the code that caused it:
```
let reqs = [
  User.upsert({
	  id: `${event.args.buyer.toLowerCase()}:${event.args.castHash}`,
	  create: {
		  ticketBalance: event.args.amount,
		  referralFeesEarned: 0n,
		  creatorFeesEarned: 0n,
	  },
	  update: ({ current }) => ({
		  ticketBalance: current.ticketBalance + event.args.amount,
	  }),
  }),
  User.upsert({
	  id: `${event.args.castCreator.toLowerCase()}:${event.args.castHash}`,
	  create: {
		  ticketBalance: 0n,
		  referralFeesEarned: 0n,
		  creatorFeesEarned: feeAmount,
	  },
	  update: ({ current }) => ({
		  creatorFeesEarned: current.creatorFeesEarned + feeAmount,
	  }),
  }),
  // some more requests  
]

await Promise.all(reqs)
```

The issue came up when I redeployed the project due to an unrelated change.

**Comment by 0xOlias** [comment]
Thanks for the bug report, this indeed looks like an edge case within Ponder. Working on a fix. Do you know if this occurred during historical or realtime indexing?

**Comment by 0xOlias** [comment]
Bump on this @benbaessler - I was able to reproduce and fix this issue in realtime, but not in historical (https://github.com/ponder-sh/ponder/pull/1072). If you can confirm that this happened while handling a new live event (not a historical event), I'll merge that and consider this completed.
