### ISSUE TITLE
multiple ponder apps on same database

### ISSUE THREAD

**Issue by edwinbernadus** [ponder-sh/ponder#1066]
is it possible to use many instance of ponder on same database?
i dont know how to rename ponder and ponder_sync schema

**Comment by 0xOlias** [comment]
The easiest way to do this is to create a new database on the same Postgres server (https://www.postgresql.org/docs/current/sql-createdatabase.html).

It's also possible for multiple Ponder apps to use the same database (sharing data in the `ponder_sync` schema) as long as they use different schemas, which is configurable in `ponder.config.ts` (https://ponder.sh/docs/api-reference/config#postgres).

Btw, we're releasing `0.6` next week which includes a full overhaul of the UX for selecting a database schema. Closing for now.
