### ISSUE TITLE
[BUG] sporadic out of order event handling with factory contracts

### ISSUE THREAD

**Issue by gte620v** [ponder-sh/ponder#1067]
I have a factory contract, `Parent`, that emits an event with the address of two children contracts, `A` and `B`.  After `A` and `B` are created, the factory makes calls to them such that they emit events.

The log sequence is:
- `Parent:CreateEvent`
- `A:ActionEvent`
- `B:ActionEvent`

In my ponder code, when I handle events from A and B, i need to do a `find` on the `Parent` event table.  If the create handler didn't fire, then there is no entry in the db.  So order of handling is critical.

This all works fine _sometimes_.  Ponder registers the children contracts, the event handling happens in order and all is good.

But sometimes, the handler for `A` and `B` fire without the `Parent:CreateEvent` ever firing.  I have verified that the logs are in order.  They are in order in the `ponder_parse` table.  But I can see in that table that the `Parent` event is not checkpointed even though the other two events, with higher `logIndex` values have been checkpointed.  

This is particularly strange since the indexer should only handle events from `A` and `B` after it has seen the `Create` event.  So these children contracts are being registered, but the event that corresponds to their creation is not sent to the handler (sometimes).

I can't reliably reproduce the error on a given event.  If i nuke the db and run again, there is a chance that the ordering is correct.  Also, this only seems to be a problem in backfill.

**Comment by gte620v** [comment]
Wow; thanks for the fast fix.  is there anything i can do before the next release to mitigate the issue?

**Comment by kyscott18** [comment]
No problem, thanks for the well written report, probably the best one we have ever gotten. 

Gonna release in ~15 minutes
