### ISSUE TITLE
intermitent telemetry test failure

### ISSUE THREAD

**Issue by 3commascapital** [ponder-sh/ponder#1093]
it looks like there are a couple of telemetry tests that fail from time to time
```
 ❯ src/common/telemetry.test.ts (3) 1486ms
   × telemetry calls fetch with event body 1081ms
   ✓ telemetry does not submit events if telemetry is disabled
   × telemetry throws if event is submitted after kill 393ms
```

at a first pass, it looks like there may be some parallelism/concurrency occurring or some cleaning up that is not occurring, causing 1 of the telemetry calls to be counted under one test, and therefore also be missing under the original.
```
 FAIL  src/common/telemetry.test.ts > telemetry calls fetch with event body
AssertionError: expected "spy" to be called 1 times, but got 0 times
 ❯ src/common/telemetry.test.ts:51:20
     49|   await telemetry.kill();
     50| 
     51|   expect(fetchSpy).toHaveBeenCalledTimes(1);
       |                    ^
     52| 
     53|   const fetchUrl = fetchSpy.mock.calls[0][0];

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/3]⎯

 FAIL  src/common/telemetry.test.ts > telemetry throws if event is submitted after kill
AssertionError: expected "spy" to be called 5 times, but got 6 times
 ❯ src/common/telemetry.test.ts:99:20
     97|   await telemetry.kill();
     98| 
     99|   expect(fetchSpy).toHaveBeenCalledTimes(5);
       |                    ^
    100| 
    101|   telemetry.record({

```

**Comment by 0xOlias** [comment]
Yes, I've seen this in our Windows CI runs. Are you seeing this locally, and if so on what OS?

**Comment by 0xOlias** [comment]
Merged an attempted fix here (https://github.com/ponder-sh/ponder/commit/02b43eb7af9d89bd63f7682dc3d9df57faf7e37a) - will revisit if there are still failures.

**Comment by 3commascapital** [comment]
still seeing this issue @0xOlias https://github.com/ponder-sh/ponder/actions/runs/10871242113/job/30164818814?pr=1085#step:6:63 i just checked the git log. this pr has already been rebased on top of that commit
