### ISSUE TITLE
bug: request transaction receipts only for filters with `includeTransactionReceipt: true`

### ISSUE THREAD

**Issue by kyscott18** [ponder-sh/ponder#1128]
### Description
Transaction receipts should only be fetched when a specific tx hash corresponds to a filter with `includeTransactionReceipts: true`.

The current logic is not granular enough and is wasteful.

https://github.com/ponder-sh/ponder/blob/5402ddcf3c751b979745c11afd6c56856e49ea68/packages/core/src/sync-realtime/index.ts#L492-L504

**Comment by khaidarkairbek** [comment]
Added the fix in the pull request above, would be perfect to get a feedback on the logic.
