### ISSUE TITLE
[Feature] Transaction call indexing

### ISSUE THREAD

**Issue by 0xOlias** [ponder-sh/ponder#113]
Ponder could support call handlers:

```ts
ponder.on("Contract:mint()", async ({ event, context }) => {
  console.log(event.input.tokenId)
})
```

This feature would only be available when using a node/RPC provider that implements the non-standard `trace_filter` method. Currently, this method is supported by:
- Alchemy
- Quicknode (with Trace Mode add-on)
- OpenEthereum and Erigon nodes

It is NOT supported by:
- Anvil
- Hardhat Network
- ~~Infura~~ (Supported as of 6/8/23)
- Moralis

**Comment by mihoward21** [comment]
Hey @0xOlias, I see this got added to the roadmap back in September. Was wondering if there's any time estimate for it? Any current workarounds? We're pretty excited about Ponder but unfortunately I think this is a blocker for us.
