### ISSUE TITLE
Validate rpc response consistency

### ISSUE THREAD

**Issue by kyscott18** [ponder-sh/ponder#1150]
## Description
Before further processing, we should validate that all referenced data is present. All `blockHash`s and `transactionHash`s should have a corresponding block and transaction. This should happen in both `sync-historical` and `sync-realtime`.

## Related 
Several users have reported that `transaction` is `undefined` in their ponder indexing functions. After further investigation this is a result of the database being corrupted, with a `log.transactionHash` referencing a transaction that doesn't exist

**Comment by khaidarkairbek** [comment]
What should be the proper handling if the log references the transaction that is not in the block? Should it throw an error?

**Comment by kyscott18** [comment]
> What should be the proper handling if the log references the transaction that is not in the block? Should it throw an error?

Great question - I think the `sync-historical` logic should log an error containing exactly what is inconsistent and then fail. `sync-realtime` should log a similar warning, and then enter this retry loop that is already used to handle some rpc-related errors.

 https://github.com/ponder-sh/ponder/blob/8790396ad61e49d284e838572c347b7c97ec9898/packages/core/src/sync-realtime/index.ts#L644-L654
 
The reason for the different behavior in `sync-historical` vs `sync-realtime` is that json rpc providers are generally less reliable (because of load balancing or reorg handilng logic or whatever reason) when the requested data is closer to the tip of the chain but eventually able to serve the correct data after retrying. Farther back in the historical range the providers are more reliable but errors are persistent.

**Comment by khaidarkairbek** [comment]
I see, can i take over this issue btw?

**Comment by kyscott18** [comment]
Yes, that would be great. I think you should start with the `sync-realtime` cause it should be more straightforward than the `sync-historical` and make a draft pr when you finish that part.

**Comment by kyscott18** [comment]
@khaidarkairbek Here's another spot in the same function we would want to update that does some rpc response validation and throws and error:
https://github.com/ponder-sh/ponder/blob/6d45c52ed32791be782181f4c04fd63fe5e01d9a/packages/core/src/sync-realtime/index.ts#L391-L395
