### ISSUE TITLE
feat: improved accuracy of `indexingCacheMaxBytes`

### ISSUE THREAD

**Issue by kyscott18** [ponder-sh/ponder#1171]
## Background
With #929, Ponder uses an in-memory cache during the historical backfill to improve the performance of indexing functions. This cache occasionally flushes to the database to avoid an out of memory error. 

The cache size is determined by `indexingCacheMaxBytes`, which is currently computed based on `os.freemem()`.
https://github.com/ponder-sh/ponder/blob/e6a0ab8e696bee7135e93fdc74b8e8792b341681/packages/core/src/common/options.ts#L108-L116

## Description
**Having a more correct (larger) cache size can significantly improve performance.**

The current calculation isn't very accurate. This is reproducible by running a Ponder app with `ponder dev -v` and looking for the log. `indexingCacheMaxBytes` on a local machine should almost certainly be multiple GB.

```sh
7:29:16 PM DEBUG indexing   Using a 64 MB indexing cache
```

Solving this issue involves a research project into which memory and then a small pr implementing the new logic, which would be (maybe) only scoped to `common/option.ts`. Ideally, we can determine the memory size at which node is going to OOM and use some percentage of that as the cache size.

### Notes
https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-mib is what we currently use to increase memory for some hosting environments.

**Comment by kyscott18** [comment]
https://nodejs.org/api/v8.html#v8getheapspacestatistics `heap_size_limit` seems quite promising

**Comment by 0xOlias** [comment]
Fixed in #1177
