### ISSUE TITLE
feat: Add ability to configure db options

### ISSUE THREAD

**Issue by grezle** [ponder-sh/ponder#1184]
I have a usecase where I'm generating a lot of writes (~1M at a time), would it be possible to allow tuning on the following options (happy to throw up a PR for this):

https://github.com/ponder-sh/ponder/blob/85781db6a22b07c8072044ce953db97abc81eb54/packages/core/src/common/options.ts#L103

https://github.com/ponder-sh/ponder/blob/85781db6a22b07c8072044ce953db97abc81eb54/packages/core/src/common/options.ts#L104

**Comment by 0xOlias** [comment]
Thanks for opening. Can you share a bit more context about what you're doing? Would like to better understand the scenario that's leading to this requirement.

Feel free to DM me on telegram (@kevinkoste) if sensitive.

**Comment by grezle** [comment]
I'll send a message over now 🙌

**Comment by kyscott18** [comment]
Just released v0.6.19, which should meaningfully improve the performance of `updateMany()`
