### ISSUE TITLE
RpcError: Hyperliquid testnet Rpc returning invalid block range for eth_get_Logs and BlockNotFoundError

### ISSUE THREAD

**Issue by khaidarkairbek** [ponder-sh/ponder#1234]
The ponder instance starts syncing and after a while exits fatally at the same block range with "invalid block range" error. I am only indexing ERC20 Transfer events. The ponder retries fetching the request, but the error persists and I think can be caused by the invalid blocks being present in the range. 

My config: 
```
PONDER_RPC_URL_998=https://api.hyperliquid-testnet.xyz/evm
```

```ts
export default createConfig({
  networks: {
    hl: {
      chainId: 998,
      transport: http(process.env.PONDER_RPC_URL_998),
    },
  },
  contracts: {
    Token: {
      network: "hl",
      abi: erc20,
      address: tokenAddresses,
      startBlock: 10531953
    },
  },
});
```
where tokenAddresses are: 
```ts
export const tokenAddresses = [
  "0xC003D79B8a489703b1753711E3ae9fFDFC8d1a82", 
  "0x34b3a8e2486D41E25d1c42cA63527437048CCdA3", 
  "0xec37d4De88D53a1ff7AC266f2F1F3F021BC4dBC7"
] as Address[]; 
```

Also, trying to run ponder with startBlock being omitted in the config (startBlock = 0), the ponder immediately returns with 
```
BlockNotFoundError: Block could not be found.
```

**Comment by kyscott18** [comment]
I think this is just a legitimate rpc bug. Requesting block 10572907 returns null, when it should be readily available in the chain

```sh
cast bl 10572907 --rpc-url https://api.hyperliquid-testnet.xyz/evm
```

**Comment by khaidarkairbek** [comment]
This is a testnet rpc issue due to hard forking, this issue shouldn't arise once mainnet is launched
