### ISSUE TITLE
RangeError: Invalid time value when using timestamp in schema

### ISSUE THREAD

**Issue by netdragonx** [ponder-sh/ponder#1240]
Not my first Ponder setup, but I was setting up a fresh one for a new app, and ran into the following error on startup:

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at PgTimestamp.mapToDriverValue

Schema for the column was defined as: `lastUpdated: t.timestamp()`

Insert for the column was also simple: `lastUpdated: new Date()`

Once I ditched `.timestamp()` in lieu of `.bigint()` I was able to start Ponder again.

**Comment by kyscott18** [comment]
Thanks for submitting this, I was able to recreate this and found a quick fix using the `withTimezone` param `timestamp({ withTimezone: true })`. Will think about a more long term solution.

 https://orm.drizzle.team/docs/column-types/pg#timestamp

**Comment by kyscott18** [comment]
I believe this was fixed in v0.7.14. Please feel free to reopen if the issue persists

**Comment by atjeff** [comment]
@kyscott18 I don't think this has been fixed. It seems to happen on (historical?) filling, something in the ponder side is creating invalid dates before they get to the drizzle/kysley layer

It may be why none of the examples use t.timestamp and use integer instead
