### ISSUE TITLE
[BUG] Running codegen does not write the schema.graphql anywhere

### ISSUE THREAD

**Issue by cuckflong** [ponder-sh/ponder#1249]
When running `ponder codegen` the `schema.graphql` file should be generated in `.generated/schema.graphql` but since version 0.7.0, it stopped working.

**Comment by cuckflong** [comment]
I noticed the code to generate `schema.graphql` is removed in v0.7.0. However I need to file for my project, any idea how I can generate that?

**Comment by 0xOlias** [comment]
Fixed in [0.7.8](https://github.com/ponder-sh/ponder/releases/tag/eslint-config-ponder%400.7.8)
