### ISSUE TITLE
Add viem ENS helpers to context client

### ISSUE THREAD

**Issue by jwahdatehagh** [ponder-sh/ponder#1271]
Is there are particular reason not to include the viem ENS helpers like `getEnsAvatar` and `getEnsText` in the client provided in the context?

**Comment by 0xOlias** [comment]
These will be added in `0.8` ([diff](https://github.com/ponder-sh/ponder/pull/1235/files#diff-ce76c224472ac0f1674a03ac1e66b76ff1c138deeee58c7922acb8c68a0dc8a7)). Planned to ship in the next couple weeks.
