### ISSUE TITLE
[Feature] Cron events

### ISSUE THREAD

**Issue by 0xOlias** [ponder-sh/ponder#353]
Sometimes, it can be useful to periodically refresh data in the indexed database. This can be difficult to do, because (at the moment) code is only triggered by log events, and you may need to perform some action at a different frequency than events are emitted.

A very common example of this is updating ERC20 price data. Here's a quick list of ways you might solve this:
1. In the `Transfer` or `Swap` event handler, call a price oracle (onchain or offchain).
2. Register a "block handler" (not currently available in Ponder, but common in subgraphs) that calls a price oracle.
3. Register an event handler for some other event that runs closer to the desired frequency and call a price oracle. (Could be an event on the oracle itself).

I wonder if a cron function is a suitable solution:

```ts
// Runs every five minutes
ponder.on("cron", "*/5 * * * *", async ({ context }) => {
  const price = await fetch("https://defillama.com/...")

  await upsert context.entities.Price(...)
})
```

Some considerations:
- The way I see it, the cron functions would only run in real-time. In other words, they would only be enabled once historical indexing is complete. So, if you need a full history of prices to support time-travel queries, you would need a different solution (probably option 1 above).
- This would be the first time we introduce an event trigger that is independent of blockchain state, so we should thread carefully.
- One massive benefit of this solution is that it doesn't slow down the historical sync _or_ historical indexing. In contrast, block handlers require Ponder to sync the entire chain, and the JSON-RPC currently only fetches one block at a time. So, this would probably have a devastating effect on sync times. This cron solution also moves this logic outside of high-frequency handlers like a `Transfer` handler, which will speed up indexing quite a lot (especially if you're using an off-chain oracle).

**Comment by shrugs** [comment]
i assumed when thinking about this solution that the cron expression would be over block.timestamp, not just real-time. perhaps a `{ historical?: boolean, realtime?: boolean }` options?

**Comment by 0xOlias** [comment]
> i assumed when thinking about this solution that the cron expression would be over block.timestamp, not just real-time. perhaps a `{ historical?: boolean, realtime?: boolean }` options?

I see, good point. Yea, perhaps this could be configurable. Would you want it to run during the historical sync to support the time-travel use case?

**Comment by shrugs** [comment]
i'll be wary of providing too much strong input since i don't have a concrete use case in mind, but yeah "computing historical pricing" is the problem statement in mind. though idk if it's the best theoretical usecase because of how one can watch individual swaps or oracle updates to appropriately sample over time.
