### ISSUE TITLE
[Feature] Direct database access

### ISSUE THREAD

**Issue by 0xOlias** [ponder-sh/ponder#370]
Today, the SQL database design (table names & encodings) is considered part of the private API - the only supported way to access this data is via the ORM within event handler functions. To unlock more flexible use cases, we'd like to add the database design to the public API.

Checklist:
- [ ] Stable/predictable table names, so downstream applications can reference tables reliably
- [x] Transparent encodings for all data types (#334)
- [ ] Documentation. We'll need to add a new page/section with answers to questions like:
  - [ ] Accessing the database (connection URL, SQLite file path)
  - [ ] How to find/predict table names
  - [ ] Mapping of schema types -> database column types by engine
  - [ ] Potential footguns

## Background

Each Ponder project repo contains one logical “app”. An app has two primary components: 1) a schema, and 2) a set of event handlers, which contain the business logic.

An app can span multiple EVM networks. For example, the app might listen to Registration events on mainnet and GameAction events on optimism. The Registration event might create an Account entity, and GameAction events might update a field on the same Account entity (eg Account.balance). When I say “multi-chain app”, I’m referring to an app that works this way.

It’s also common for apps to be deployed to multiple environments. In the single chain case (vast majority of apps today), people use EVM chains as environments. A common example would be:
Local -> Anvil
“Staging”/Testnet -> Goerli
Prod -> Mainnet

Most people don’t think about it this way - they refer to it as local/testnet/mainnet. Environments and networks are interchangeable in their worldview.

In the multichain case, this looks like:
Local -> Anvil 1 + Anvil 2
Staging/testnet -> Goerli + Optimism Goerli
Prod -> Mainnet + Optimism mainnet

While it’s quite rare for folks to build multi-chain apps today, I have a hunch that it’s going to become more common, so I’d like Ponder to support it from day one. It actually already does - this table namespacing issue is one of the last sticking points.

IMO the challenge is finding a solution that satisfies the above requirements without confusing folks who think entirely in a single-chain app world. There’s already a ton of confusion for people who use the term “multichain” to mean “I have my app deployed on both goerli and mainnet”.

## Proposal

- Add a required “name” field to ponder.config.ts. This represents the top-level namespace for the app. An app has a single schema and a single set of event handlers.
- Adopt a pattern where an app has one config file per environment. For the vast majority of single-chain apps today, this would look like:
```
/my-ponder-app
  ponder.config.ts  <- local
  ponder.goerli.config.ts
  ponder.mainnet.config.ts
```
A multichain app might look like:
```
/my-ponder-app
  ponder.config.ts  <- local
  ponder.testnet.config.ts OR ponder.staging.config.ts
  ponder.mainnet.config.ts OR ponder.prod.config.ts
```

- Use `{app_name}-{environment_name}-{table_name}` as a stable name for database views that are backed by the latest version of the table. Zero-downtime deployments happen at the {app_name}-{environment_name} level. During a ZDD, the "new" instance updates the views to point at its tables (just like we're doing in #335).

I like this, and I think it's 90% correct. One potential annoyance is that users will need to repeat some information in their config files - notably, the new `"name"` field, as well as most of the `contracts`/`filters`/`factories` stuff. Also, I really don't know how the Foundry integration will actually look, and if it'll be intuitive alongside this pattern. There's also the broader annoyance of ABI/address management, but that's kind of a separate issue.

**Comment by jacek0x** [comment]
Just some thoughts on the database stuff:

1. **Table Names**: We're dealing with camel case in ORM, right? Kinda annoying in Postgres since you gotta use double quotes all the time. Snake case would be way smoother.

2. **Schema Stuff**: How about letting us set up a specific schema for Ponder? Right now, everything goes into the public schema unless you're doing the extra step of creating a Ponder DB user. Would be neater to have it all in its own space.

3. **Views on Event Tables**: Would be super cool if we could create views on the tables that have event data and get to them through the API. Would make things a lot easier to handle.

**Comment by faces-of-eth** [comment]
Came here to +1 this as someone who is interested in the indexing data and blending it with other information to present a unified API

<img width="292" alt="image" src="https://github.com/ponder-sh/ponder/assets/108703161/74166d53-c6a6-4c78-97e6-e3758fced239">

As is right now, pretty impossible to deal with at the database level
