### ISSUE TITLE
Node v.18.0.0 is unsupported

### ISSUE THREAD

**Issue by faces-of-eth** [ponder-sh/ponder#541]
<img width="814" alt="image" src="https://github.com/ponder-sh/ponder/assets/108703161/7902c0e2-b92c-4855-bacb-e3c5a2ffa6da">

**Problem**

Attempting to create a project with Node v18.0.0 gives me the following error `os.AvailableParallelism is not a function`.

**Expectation**

Either Node 18 should be supported, or an error message should be provided letting me know that it's not supported.

**Fix**

Upgrading to latest Node version worked.

**Comment by kyscott18** [comment]
Thanks for submitting this! It looks like `os.parallelism` was added in [v18.14.0](https://nodejs.org/download/release/latest-v18.x/docs/api/os.html#osavailableparallelism), so I will get this resolved.
