### ISSUE TITLE
"Indexing (not started)" is the only output I receive when errors are present in my index 

### ISSUE THREAD

**Issue by faces-of-eth** [ponder-sh/ponder#542]
![telegram-cloud-photo-size-1-5183692606633258548-y](https://github.com/ponder-sh/ponder/assets/108703161/9e0d883c-ffa0-44a8-b679-f4ca6f0cdd87)

**Problem**

Starting a project using `yarn create ponder`, then selecting the `Reference - ERC721` template option does not produce running code.

**Solution**

It seems like using the default ABI reference implementation is causing the issue. Creating a custom ABI file and not using the provided `erc721ABI` from `@wagmi/core` fixed the issue for me and started indexing again.

**Expectation**

I tried setting `PONDER_LOG_LEVEL="debug"`, hoping some more information would be presented to me inside of the dev log. Nothing was shown. It would be a nicer dev experience if some form of error were provided instead of silently erroring out.

**Comment by 0xOlias** [comment]
Hi @faces-of-eth thanks for the detailed report! I just tried to reproduce using `0.1.3` and was not able to. Which version were you using? Also, if you could try to reproduce again using `0.1.3` that would be helpful.
