### ISSUE TITLE
Possible memory leak cause

### ISSUE THREAD

**Issue by faces-of-eth** [ponder-sh/ponder#550]
<img width="614" alt="image" src="https://github.com/ponder-sh/ponder/assets/108703161/7d5b5270-1bc7-4993-91a1-3f9e9a9c9cca">

Indexing for around 30m or so I started to encounter these messages when setting log level to debug. I believe this perhaps might be related to the memory leak discussed in dev chat a few days ago.

**Comment by kyscott18** [comment]
Is this an already synced ponder app or did you start from zero?

**Comment by faces-of-eth** [comment]
This is a sync that I had been starting and stopping all day long. I had not cleared the .ponder directory before encountering this issue, which is what I imagine a “sync from zero” scenario might be? LMK if I can clarify any other issues.

**Comment by 0xOlias** [comment]
Fixed in [0.1.8](https://github.com/ponder-sh/ponder/releases/tag/%40ponder%2Fcore%400.1.8)
