### ISSUE TITLE
Turn off GraphQL server

### ISSUE THREAD

**Issue by faces-of-eth** [ponder-sh/ponder#561]
Sort of piggybacking on [Issue 514](https://github.com/ponder-sh/ponder/issues/514) I think it might be helpful to turn off the GraphQL server completely for certain people.

Currently I'm using Ponder and Reservoir Light Sync Nodes to dump everything into a Supabase database, then using its built-in GraphQL server so I can query the union of data.

In this setup, the GraphQL server for Ponder doesn't add much benefit for me, and mostly only overhead.

**Comment by jborichevskiy** [comment]
@faces-of-eth - curious how you get the event data into Supabase itself? if you are considering turning off the grahpql endpoint I assume you have an external service reading ponder db and writing into supabase? or another way? 

thanks

**Comment by faces-of-eth** [comment]
> @faces-of-eth - curious how you get the event data into Supabase itself? if you are considering turning off the grahpql endpoint I assume you have an external service reading ponder db and writing into supabase? or another way?
> 
> thanks

Hey! By default Supabase exposes a graphql endpoint (https://supabase.com/docs/guides/graphql), and you can simply point ponder at Supabase via a postgres connection URL. 

I've moved away from this particular setup and Ponder for the moment in particular because of other things the team is actively working on, but just not quite ready for my needs. Will be back to evaluate in a few versions when it's a bit more mature!
