### ISSUE TITLE
Missing events on chains other than mainnet

### ISSUE THREAD

**Issue by technophile-04** [ponder-sh/ponder#580]
## Context :

We have basic ponder.sh repo setup, which is indexing events of multiple contracts(same abi) on `mainnet` and same for `optimism`.

<details>
  <summary>
    Here is our ponder.config.ts
  </summary>

```ts
const mainnetCohorts = [
  // Main Hacker House (Jessy's)
  "0x2Be18e07C7be0a2CC408C9E02C90203B2052D7DE",
  // Infrastructure (Jessy's)
  "0x502730421b796baeeB9D907d88685234dDb44750",
  ...
] as `0x${string}`[];

const optimismCohorts = [
  // Sand Garden (old)
  "0x2eA63c9C9C114ae85b1027697A906420a23e8572",
  // Sand Garden (new)
  "0x964d0C9a421953F95dAF3A5c5406093a3014A5D8",
  // 0xAfro
  "0x3DDb71FB2b6Fb530615FC1dEb9461d6489EDA1ff",
  ...
] as `0x${string}`[];

export default createConfig({
  networks: {
    mainnet: {
      chainId: 1,
      transport: http(process.env.PONDER_RPC_MAINNET),
      pollingInterval: 15_000,
    },
    optimism: {
      chainId: 10,
      transport: http(process.env.PONDER_RPC_OPTIMISM),
      pollingInterval: 15_000,
    },
  },
  contracts: {
    CohortContract: {
      abi: CohortContractAbi,
      network: {
        mainnet: {
          // This can be multiple addresses []
          address: mainnetCohorts,
          startBlock: 16992407,
        },
        optimism: {
          address: optimismCohorts,
          startBlock: 101114639,
        },
      },
    },
  },
});
```

</details>

<details>
  <summary>
    Here is our ponder.schema.ts
  </summary>

```ts
export default createSchema((p) => ({
  CohortBuilder: p.createTable({
    id: p.string(),
    amount: p.float(),
    cohortContractAddress: p.bytes(),
    timestamp: p.bigint(),
    ens: p.string().optional(),
  }),
  CohortWithdrawal: p.createTable({
    id: p.string(),
    builder: p.bytes(),
    amount: p.float(),
    cohortContractAddress: p.bytes(),
    reason: p.string(),
    timestamp: p.bigint(),
  }),
}));
```

</details>

## Problem :

It seems that for some reason while querying the events for contracts on optimism, we are not getting events data before approx 15/11/2023 (this is not exact data but approx based on observation).It works nicely for `mainnet` contracts

Also just to be sure we also checked `startBlock` for optimism, and it seems to be correct we are using [`101114639`](https://optimistic.etherscan.io/block/101114639) which was minned on May.

To cross-verify you could run the below query on https://bg-ponder-indexer-production.up.railway.app/ :

<details>
  <summary>
    query
  </summary>
  
```graphql
query Withdrawls {
  cohortWithdrawals(
    where: {
      cohortContractAddress: "0x3DDb71FB2b6Fb530615FC1dEb9461d6489EDA1ff"
    }
    orderBy: "timestamp"
    orderDirection: "desc"
  ) {
    reason
    builder
    amount
    timestamp
    cohortContractAddress
    id
  }
}
```

</details>

And checkout "Contribution" section of https://0xafro.vercel.app/ (it may take some time here to load all contribution since we are currently brute force looping over all contract logs)

Would love to know if its something we missing on our end and if so what is the best way to debug this, also a naive question if we change something will it re-index whole thing ?

Tysm guys for building such an awesome tool 🙌 !!

**Comment by 0xOlias** [comment]
Hi @technophile-04, thanks for the thorough report. 

I ran your app with a single indexing function:
```ts
import { ponder } from "@/generated";

ponder.on("CohortContract:AddBuilder", async ({ event, context }) => {
  const timestamp = new Date(Number(event.block.timestamp) * 1000);
  console.log(timestamp, context.network.chainId);
});
```

And got the following console output:
```
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-06T22:09:59.000Z 1
2023-04-10T20:54:59.000Z 1
2023-05-09T09:16:11.000Z 1
2023-05-24T15:37:56.000Z 10
2023-05-24T15:37:56.000Z 10
2023-05-24T15:37:56.000Z 10
2023-05-24T15:37:56.000Z 10
2023-05-27T16:22:47.000Z 1
2023-06-01T13:55:59.000Z 1
2023-06-27T10:38:51.000Z 10
2023-06-30T21:19:09.000Z 10
2023-06-30T21:19:09.000Z 10
2023-07-30T14:43:11.000Z 10
2023-09-21T07:15:07.000Z 10
2023-12-01T19:21:49.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
2023-12-06T11:44:51.000Z 10
5:45:56 PM INFO  indexing   Indexed 35 events up to Dec 6, 2023 (chainId=10 block=113132157 logIndex=10)

Historical sync (complete)

Indexing (up to date)
████████████████████████████████████ 100% | 35/35 events (163 total)
```

So, at a glance, it looks like I'm getting optimism events before November 2023. Does this output look like what you'd expect?

One possible source of the issue is that the database you're running on Railway has a corrupted cache (this would be a bug on our end). Please try deleting the database service, and starting your app again using a new database, and let me know if the problem persists.

**Comment by technophile-04** [comment]
TYSM @0xOlias for the quick response !! 

> Please try deleting the database service, and starting your app again using a new database, and let me know if the problem persists.

Yup doing this solve the issue !!! 

> database you're running on Railway has a corrupted cache (this would be a bug on our end).

Ohh makes sense !! 

Please feel free to close the issue, thanks again! 🙌

**Comment by 0xOlias** [comment]
Glad to hear it @technophile-04. To help us debug the root cause here, could you share which RPC node/provider you were using to sync the initial (bugged) database? One known cause of this issue is syncing against a pruned node.

**Comment by technophile-04** [comment]
Hey really sorry for late reply 

> could you share which RPC node/provider you were using to sync the initial (bugged) database?

We are using Alchemy node
