### ISSUE TITLE
Column `chainId` type should be `bigint`

### ISSUE THREAD

**Issue by wuminzhe** [ponder-sh/ponder#593]
postgres type `integer` is 4 bytes length with a range between -2147483648 and +2147483647.

1. But,some evm's chain ids are bigger than this. https://chainid.network/chains_mini.json
2. And, the geth use bigint. https://github.com/ethereum/go-ethereum/blob/6b0de79935110fb5f63a60288191848dd98980ea/params/config.go#L42

**Comment by 0xOlias** [comment]
Thanks for opening. Did you run into an error related to this?

**Comment by wuminzhe** [comment]
> Thanks for opening. Did you run into an error related to this?

yes, I did.
