### ISSUE TITLE
Support field similar to graph's  `_meta { block: { number } }`

### ISSUE THREAD

**Issue by eldimious** [ponder-sh/ponder#647]
Hello, i am using ponder and subgraph to get prices for some tokens, therefore on api side, i want to make sure that the returned data from subgraph are using the latest chain block, and are not stuck in previous blocks. 
Therefore on the api side when i query data, i would like to query a property that returns the latest injected / processed block for this specific subgraph.
On graph node there is a property called `_meta { block: { number } }` which returns the latest injected block number for the subgraph.

Can we add something similar on ponder? Thanks!

**Comment by 0xOlias** [comment]
Fixed in #963
