### ISSUE TITLE
docs link 404s

### ISSUE THREAD

**Issue by o-az** [ponder-sh/ponder#653]
[options.maxHealthcheckDuration](https://ponder.sh/api-reference/ponder-config#options) in this section 404s: https://ponder.sh/api-reference/ponder-config#options

**Comment by 0xOlias** [comment]
I think you might have had a cached old version of the docs running when you found this? That link is no longer working for me (we renamed the `ponder-config` path to just `config`)

**Comment by o-az** [comment]
> I think you might have had a cached old version of the docs running when you found this? That link is no longer working for me (we renamed the `ponder-config` path to just `config`)

Visiting here in incognito mode: https://ponder.sh/docs/guides/production#zero-downtime-deployments the `options.maxHealthcheckDuration` at the end of the first paragraph of the zero downtime deployment section still 404s
