### ISSUE TITLE
Support more than 10000 children when using factory contracts

### ISSUE THREAD

**Issue by Destiner** [ponder-sh/ponder#673]
Currently, factory contract support is limited in the amount of child instances you can index.

As per [docs](https://ponder.sh/docs/guides/add-contracts#factory-contracts):

> **Scaling**: The sync engine does not currently support factory contracts with more than 10,000 children. This includes Uniswap V2, V3, and many other permissionless pool-based DeFi protocols. Why not? The Ethereum JSON-RPC API does not scale well for factory contracts. There's only so much that Ponder's sync engine can do about this while remaining compatible with the JSON-RPC API. We're actively working to address scaling challenges via features like remote sync, shared caching, and concurrent indexing. Thanks for your patience.

Ideally, it would be possible to extend to unlimited number of children.

**Comment by Destiner** [comment]
Made an issue mostly for tracking purposes, but have you explored shifting to full block log querying once you exceed the threshold?

E.g. start with a narrow `eth_getLogs` query filtering by instance addresses (I think that's how it works now?), and then switch to an unfiltered `eth_getLogs` query once the number of instances exceed 10000.

**Comment by kyscott18** [comment]
Fixed this starting in 0.5.19
