### ISSUE TITLE
Bug: Instace stuck due to wrong block parameters

### ISSUE THREAD

**Issue by luziusmeisser** [ponder-sh/ponder#714]
My ponder instance got stuck due to the following error. Note that fromBlock is *after* the toBlock in the parameters. This looks like an error to me. The blocks in question did exist at this point in time, so the error message received from the node (alchemy) is also wrong. I suspect that the reason the node could not find the block is that the specified toBlock was after the fromBlock. But that's just a guess.

6:35:03 AM WARN  realtime   Realtime sync task failed (network=mainnet, error=InvalidInputRpcError: Missing or invalid parameters.

Double check you have provided the correct parameters.

URL: https://eth-mainnet.g.alchemy.com/v2/...

Request body: {"method":"eth_getLogs","params":[{"fromBlock":"0x128b7d5","toBlock":"0x128b7d4","topics":[["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925","0x72fba0ba07d937c660a3130fca36005c0e476cb97b6f00de413976e37eba9501","0x97326258efdae63280617ca33884e507791c2abeed7b82acd77f1853394ef94b","0xd60c86e83346fdbe3124cb7d1cba32973a9f62d05c4ec801bfe6c09d10380381","0x5314098314219d6e1ce8e41fc5e6ec1ce2f06a9d583079fb6619af9bf6efdf41","0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925","0xd000f39f92c3ed77f890f16b6ced1555e0ab2cdf470522d2210de67d8c83d45b","0xd98fb7c2b7c7b545387da80b92c08bc5d2a4b922fb74851c3d27ee07ca897bdf","0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x1eee30d91b773ac47d7485a3acb6bcd8c7c9cd8d95301b1af361baf5f0991d2e","0xc4b384b2c5ca32c8e77081f4083be594a1ea9ba34f208a9f9a458f70608585f5","0x7d3a26e8d43c5b70f86266bfa26c212e3c097716ff7240ccb6a9034e48754e23","0x591ede549d7e337ac63249acd2d7849532b0a686377bbf0b0cca6c8abd9552f2","0x8ab298b78a235f73eee230f82012c0cf4db76003eaabd16a0195f112e7d625c8","0x591ede549d7e337ac63249acd2d7849532b0a686377bbf0b0cca6c8abd9552f2","0xcb2040b7eb3265a4335698c9ecbe81a5f9857e92aa32e07ce235f44c321a7e35","0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0","0xaca80c800ec0d2aa9d9d31b7f886a1dd3067d4676abc637626a18ffb9381653d"]]}]}

Details: One of the blocks specified in filter (fromBlock, toBlock or blockHash) cannot be found.

**Comment by kyscott18** [comment]
Appreciate you creating this issue. What version of `@ponder/core` are you on? We fixed several issues in the realtime service recently and I would recommend upgrading to `v0.3.3` if you haven't.

**Comment by luziusmeisser** [comment]
Good hint, it looks like we are actually running on v0.2.5
