### ISSUE TITLE
[Bug]: StoreError - Cannot update record because there is a newer version of the record.

### ISSUE THREAD

**Issue by XmoDVO** [ponder-sh/ponder#738]
## description

updating record run into error when indexing historical data.

![image](https://github.com/ponder-sh/ponder/assets/128128121/6f93f919-2e0a-4a6e-8442-7b5fbe7b8f44)

The error will disappear if I restart the project by `ctrl + c` && `npm run dev`, but it probably lose some data if I do so and it is unacceptable.

## code

contract: `0xf087c864AEccFb6A2Bf1Af6A0382B0d0f6c5D834` at `zksync era`

```typescript
import { Context, ponder } from '@/generated';
import { Address, zeroAddress } from 'viem';
import { assets } from '../public/assets';

ponder.on('PythContract:PriceFeedUpdate', async ({ event, context }) => {
  const id = event.args.id;

  const { PythPrice } = context.db;
  const asset = assets.find((asset) => asset.pythFeedId === id);
  if (!asset) {
    await PythPrice.upsert({
      id,
      create: {
        price: event.args.price,
        conf: event.args.conf,
        publishTime: Number(event.args.publishTime),
        address: zeroAddress,
        symbol: '',
        decimal: 0,
        expo: 0,
      },
      update: {
        price: event.args.price,
        conf: event.args.conf,
        publishTime: Number(event.args.publishTime),
      },
    });
    return;
  }

  await PythPrice.upsert({
    id,
    create: {
      price: event.args.price,
      conf: event.args.conf,
      publishTime: Number(event.args.publishTime),
      address: asset.address,
      symbol: asset.symbol,
      decimal: asset.decimals,
      expo: asset.expo,
    },
    update: {
      price: event.args.price,
      conf: event.args.conf,
      publishTime: Number(event.args.publishTime),
    },
  });
});
```

**Comment by 0xOlias** [comment]
Hi @XmoDVO, appreciate the thorough bug report. We're looking into this and will get back to you soon.

In the meantime, you should be safe to reload/redeploy - I don't think this will cause lost data as you suggest. If you have evidence that there is invalid data in the database after encountering this error, please share.

**Comment by XmoDVO** [comment]
> Hi @XmoDVO, appreciate the thorough bug report. We're looking into this and will get back to you soon.
> 
> In the meantime, you should be safe to reload/redeploy - I don't think this will cause lost data as you suggest. If you have evidence that there is invalid data in the database after encountering this error, please share.

sorry, the losing data error is actually an "realtime" error, not related to this one.
