### ISSUE TITLE
Database error while running insertLogFilterInterval, Cannot use a pool after calling end on the pool

### ISSUE THREAD

**Issue by jiguantong** [ponder-sh/ponder#769]
![image](https://github.com/ponder-sh/ponder/assets/27564714/f117c173-888e-416a-99b3-2851d0efe1bd)

This error will appear after running for a period of time (about 3 days), but our database is working normally

**Comment by 0xOlias** [comment]
Thanks for reporting. Couple questions:
1. What version of @ponder/core?
2. Are you running `ponder dev` or `ponder start` here?
3. If you search the logs for "fatal", are there any hits?

**Comment by fewensa** [comment]
1. https://github.com/darwinia-network/ormponder/blob/3004a3010e2ba7f7d0b09220749b6d2a35e8406f/package.json#L14
2. https://github.com/darwinia-network/ormponder/blob/3004a3010e2ba7f7d0b09220749b6d2a35e8406f/Dockerfile#L11
3. no output
  ```
  cat ormponder.log | grep fatal
  ```

**Comment by jiguantong** [comment]
> 1. ["@ponder/core": "^0.3.4",](https://github.com/darwinia-network/ormponder/blob/3004a3010e2ba7f7d0b09220749b6d2a35e8406f/package.json#L14)
> 2. [yarn start](https://github.com/darwinia-network/ormponder/blob/3004a3010e2ba7f7d0b09220749b6d2a35e8406f/Dockerfile#L11)
> 3. no output
> 
> ```
> docker logs ormponder-index >& ormponder.log
> cat ormponder.log | grep fatal
> ```

@0xOlias Can yo help this?

**Comment by wuminzhe** [comment]
postgres or sqlite?

**Comment by jiguantong** [comment]
> postgres or sqlite?

I have got this error when using sqlite in the development environment, and also got it when using postgres in the production environment.

**Comment by 0xOlias** [comment]
@jiguantong are you still running into this issue?

**Comment by jiguantong** [comment]
> @jiguantong are you still running into this issue?

Nope. I will continue to observe in the test environment for a while.

**Comment by 0xneves** [comment]
I'm having a similar issue while synching with a new blockchain (evm type)

![pondererrror](https://github.com/ponder-sh/ponder/assets/90667119/15b2a798-5d8a-41f2-8af9-12ba45558e97)
