### ISSUE TITLE
Possible EventTarget memory leak detected

### ISSUE THREAD

**Issue by jiguantong** [ponder-sh/ponder#781]
["@ponder/core": "^0.3.4",](https://github.com/darwinia-network/ormponder/blob/3004a3010e2ba7f7d0b09220749b6d2a35e8406f/package.json#L14)

[yarn start](https://github.com/darwinia-network/ormponder/blob/3004a3010e2ba7f7d0b09220749b6d2a35e8406f/Dockerfile#L11)

![image](https://github.com/ponder-sh/ponder/assets/27564714/b2df4720-644e-4fbb-80fe-f90e3bbac92f)

**Comment by 0xOlias** [comment]
Fixed in https://github.com/ponder-sh/ponder/pull/922
