### ISSUE TITLE
[Bug]: ponder serve out of memory error

### ISSUE THREAD

**Issue by XmoDVO** [ponder-sh/ponder#787]
ponder version: 0.3.11;
network: zksync era;
script: `ponder serve`

```
(node:323) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 146 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
```

![image](https://github.com/ponder-sh/ponder/assets/128128121/71fe09bc-ae32-4a58-8d06-6cd6ba833d00)

**Comment by 0xOlias** [comment]
Hi @XmoDVO, thanks for reporting. If possible, could you please update to `0.4` and let me know if you still have this issue?

**Comment by 0xOlias** [comment]
Fixed in https://github.com/ponder-sh/ponder/pull/922
