### ISSUE TITLE
It is not suitable when dealing with networks that produce blocks quickly, because the range may be very large

### ISSUE THREAD

**Issue by jiguantong** [ponder-sh/ponder#807]
https://github.com/ponder-sh/ponder/blob/%40ponder/core%400.4.4/packages/core/src/sync-realtime/service.ts#L456

**Comment by 0xOlias** [comment]
Hi @jiguantong, thanks for opening. We're running Ponder apps that index Arbitrum in realtime without issue.

I can think of two reasons why your app might not be able to keep up:
1. The `maxRequestsPerSecond` setting on your network is not high enough (https://ponder.sh/docs/api-reference/config#networks)
2. You're using the `rateLimit` transport (https://ponder.sh/docs/utilities/transports#rate-limit) with a `requestsPerSecond` that is not high enough 
3. The latency of the RPC URL you are using is significant

If adjusting these settings does not solve your issue, please share your network config and RPC provider so we can attempt to reproduce.

**Comment by jiguantong** [comment]
> Hi @jiguantong, thanks for opening. We're running Ponder apps that index Arbitrum in realtime without issue.
> 
> I can think of two reasons why your app might not be able to keep up:
> 
> 1. The `maxRequestsPerSecond` setting on your network is not high enough (https://ponder.sh/docs/api-reference/config#networks)
> 2. You're using the `rateLimit` transport (https://ponder.sh/docs/utilities/transports#rate-limit) with a `requestsPerSecond` that is not high enough
> 3. The latency of the RPC URL you are using is significant
> 
> If adjusting these settings does not solve your issue, please share your network config and RPC provider so we can attempt to reproduce.

You are right. We set a low maxRequestsPerSecond.

Do you think this could be optimized? Avoid using getBlock for each block, because a large number of requests, the level of paid RPC must be upgraded.

**Comment by 0xOlias** [comment]
To properly handle reorgs, the realtime sync must fetch every block. This can get costly on fast chains like Arbitrum. We're looking into an alternative version of the realtime sync that is not safe to reorgs, but makes fewer RPC requests. Will let you know once we've made more progress on it.

I'm going to close this issue for now.
