### ISSUE TITLE
Need to isolate checkpoints for different chains

### ISSUE THREAD

**Issue by xiaoch05** [ponder-sh/ponder#869]
Different chains use the same checkpoint for comparison, without distinguishing between them, resulting in inaccurate checkpoints for each chain.

see https://github.com/ponder-sh/ponder/blob/fc26111ec8a82352f1fe10fc6d4767b1429eafd3/packages/core/src/sync/service.ts#L113

**Comment by 0xOlias** [comment]
Thanks for opening. Could you please provide more details, and/or an example scenario to demonstrate the bug?

**Comment by xiaoch05** [comment]
> Thanks for opening. Could you please provide more details, and/or an example scenario to demonstrate the bug?

We use a single checkpoint in syncService to cache the latest checkpoint. But all the networks, such as Ethereum, Polygon, etc., would update this checkpoint. Then in fact they can't compare with each other because they are different chains and have different blocks. Is my understanding correct?

**Comment by hackfisher** [comment]
> Thanks for opening. Could you please provide more details, and/or an example scenario to demonstrate the bug?

https://docs.envio.dev/docs/multichain-indexing#unordered-multichain-mode

This doc from envio explained the scenario and requirement of so called `unordered-multichain-mode`

**Comment by 0xOlias** [comment]
> > Thanks for opening. Could you please provide more details, and/or an example scenario to demonstrate the bug?
> 
> https://docs.envio.dev/docs/multichain-indexing#unordered-multichain-mode
> 
> This doc from envio explained the scenario and requirement of so called `unordered-multichain-mode`

Thanks for sharing. At the moment, Ponder only supports "ordered multichain mode". The mechanism for ordering events across chains uses:
1. Block timestamp
2. Chain ID
3. Block number
4. EVM execution index (could be transaction index, log index, etc)

As far as I can tell, the checkpoint ordering logic in the syncService is working as expected - checkpoints _can_ be compared across different chains.

Closing this issue for now - @xiaoch05 please feel free to re-open if you have a bug.
