### ISSUE TITLE
[Bug] Fix multicall on base

### ISSUE THREAD

**Issue by taarushv** [ponder-sh/ponder#876]
Not sure if there's a way to manually set the multicall contract for each network but it doesn't seem to work out of the box with base, forcing me to create/use a custom viem client. Replacing the client (to viem with base as the defined chain) below fixes my issue, despite using the same RPC on both runs

```
    const results = await client.multicall({
        contracts: [
          {
            ...ClubsV2Contract,
            functionName: "name",
            args: [event.args.id],
          },
          {
            ...ClubsV2Contract,
            functionName: "uris",
            args: [event.args.id],
          },
          {
            ...ClubsV2Contract,
            functionName: "coefficients",
            args: [event.args.id],
          }
        ],
      })
   ```
   
   ` "@ponder/core": "^0.4.22"`

**Comment by 0xOlias** [comment]
Got it. We're planning to make it possible to pass a viem `Chain` as an option to `networks`, which would solve this issue. Still working out the details of the API and migration path, cc @kyscott18.

In the meantime, you might be able to construct the multicall request using `context.client.readContract`, which means you'd still benefit from caching. The custom client approach will slow down reindexing significantly.

**Comment by kyscott18** [comment]
This can be fixed using extra parameters for multicall

https://viem.sh/docs/contract/multicall#multicalladdress-optional
