### ISSUE TITLE
[Feature] Support blockTag on readContract/multicall

### ISSUE THREAD

**Issue by taarushv** [ponder-sh/ponder#877]
I'm trying to index data on base using ponder. Running a full node instead of an archive node (due to size constraints). I didn't think it'd be much of an issue because most of the data I need can be derived from events (which the full node returns). But when I started to work on contract calls to read chain state, I noticed that I'm forced to create a custom viem client. This is because for old events when readContract defaults to `blockNumber: event.block.number`, the underlying eth_calls fail with trie node missing error, since it is not an archive node. 

Fortunately, the contract I'm working with is a one time set/get that doesn't update the variables I'm trying to read, which means if I can make the same eth_calls at latest block height, it both doesn't fail and returns the correct data I need. But to accomplish that (since `blockTag: "latest"` isn't supported) I'm doing: 

  ```
  const latestBlock = await customViemClient.getBlockNumber() 
  const results = await ponderClient.multicall({
        contracts: [
          {
            ...ClubsV2Contract,
            functionName: "name",
            args: [event.args.id],
          },
          {
            ...ClubsV2Contract,
            functionName: "uris",
            args: [event.args.id],
          },
          {
            ...ClubsV2Contract,
            functionName: "coefficients",
            args: [event.args.id],
          }
        ],
        blockNumber: latestBlock,
     })
```

This would require me to roll my own error handling/retries or write to db with default values if the rpc call fails and fix later, blockTag support would solve this. I could also just hardcode it to a recent block (if the scope was only backfill) but have to get latest block number to make sure I can process new incoming events/their on-chain metadata. 

Is there a better pattern to index with full nodes that I'm missing? without backfilling first with a hardcoded blockNumber, copying tables and then rerunning with a new startBlock for the contract

**Comment by kyscott18** [comment]
You should pass the `cache: "immutable"` property to multicall. It uses "eth_call" with `blockNumber: "latest"` and then caches the result. Any requests with the same parameters will be served from the cache, regardless of what block the event was in.

```js
const results = await ponderClient.multicall({
      contracts: [
        {
          ...ClubsV2Contract,
          functionName: "name",
          args: [event.args.id],
        },
        {
          ...ClubsV2Contract,
          functionName: "uris",
          args: [event.args.id],
        },
        {
          ...ClubsV2Contract,
          functionName: "coefficients",
          args: [event.args.id],
        }
      ],
      cache: "immutable"
   })
```

**Comment by taarushv** [comment]
Sweet, tested and it works as intended, thanks!
