### ISSUE TITLE
[BUG] Ponder.on not fetching all events when there are more than one network in `ponder.config.ts` 

### ISSUE THREAD

**Issue by RafaDSan** [ponder-sh/ponder#883]
### Version 
`"@ponder/core": "^0.4.7"`

### Bug Found
`ponder.on` not fetching all swaps from a network when there are more than one network in `ponder.config.ts`

#### 1. Result of running `npm run dev` with commentend network:

![image](https://github.com/ponder-sh/ponder/assets/102108966/a0508c2b-34bd-4f47-a264-27b2cff6f749)
![image](https://github.com/ponder-sh/ponder/assets/102108966/6e78515f-3f93-4d41-9f03-f6f3d5fabf14)

#### 2. Result of running `npm run dev` with uncommented network:

![image](https://github.com/ponder-sh/ponder/assets/102108966/e74aeed0-e5ea-4325-bac6-d6a19368a3d1)
![image](https://github.com/ponder-sh/ponder/assets/102108966/e2b3e3dc-53bd-4443-839a-86ac5dd78906)

### Steps to reproduce

1. clone [this](https://github.com/RafaDSan/swaplace-subgraph/tree/ponder) repository
2. Uncomment the `kakarot` network on the `ponder.config.ts` file 
3. Run `npm run dev`

### Additional Context
This `kakarot` network is still on alpha, and we have another issue related to the network in [this](https://github.com/ponder-sh/ponder/issues/818) issue
https://sepolia.kakarotscan.org/address/0xB317127b50b22e62637E3c333A585a8ccfd0721D?sort=asc

### Update
I've updated the ponder to the version ` "@ponder/core": "^0.4.24"` and it fetched all the events for the `sepolia` network, but not for `kakarot`, where it only brought 3 events, instead of 10, as shown in [this](https://sepolia.kakarotscan.org/address/0xB317127b50b22e62637E3c333A585a8ccfd0721D/events) link

**Comment by 0xOlias** [comment]
Closing per https://github.com/ponder-sh/ponder/issues/886#issuecomment-2116600371

**Comment by swetshaw** [comment]
Tried ponder on multiple networks, it is able to correctly index events from all the networks (screenshot attached). We can mark this issues closed.

<img width="661" alt="Screenshot 2024-08-07 at 3 35 30 PM" src="https://github.com/user-attachments/assets/d06e7eb7-5190-4056-886d-4cf9e43ba154">
