### ISSUE TITLE
EVM Network works on Subgraph but not on Ponder

### ISSUE THREAD

**Issue by RafaDSan** [ponder-sh/ponder#908]
The Kakarot network is working to solve its RPC problems, and now the issue mentioned below has been solved.

Also, we are testing fetching the events on the Kakarot network with the Subgraph as well, and the Subgraph correctly fetched the events in the Kakarot network (prints below).

What info can I provide to you to help us debug this problem and to fetch the events in the Kakarot network using Ponder?

> @kyscott18 started working on a reproduction here, and found another Kakarot RPC bug.
> 
> It looks like [EIP-234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md) `eth_getLogs` requests return all logs on the chain, regardless of which block they were emitted in. Can reproduce with this request:
> 
> ```
> curl -X POST -H "Content-Type: application/json" --data '{
>     "jsonrpc": "2.0",
>     "method": "eth_getLogs",
>     "params": [{
>         "blockHash": "0x020dc933dc5772707a9b78f76010b2c538d3e55423646481ccefa56ae0a7e887"
>     }],
>     "id": 1
> }' https://sepolia-rpc.kakarot.org
> ```
> 
> We work hard to triage, reproduce, and fix every bug report that we receive. It’s time-consuming work. Unfortunately, after two incidents of non-compliance, we can’t accept bug reports for apps using Kakarot until we see evidence that they are thoroughly testing their RPC ([related issue](https://github.com/kkrt-labs/kakarot-rpc/issues/1055)).
> 
> Closing for now. There may indeed be a Ponder bug here, and we will gladly revisit once the Kakarot RPC test coverage has improved.

### Endpoint running GraphQL queries returning the events emitted on the Kakarot network
![image](https://github.com/blockful-io/swaplace-subgraph/assets/102108966/1b9b9090-24f9-4d8f-ba93-d11c492d5423)

### [Kakarot scan](https://sepolia.kakarotscan.org/address/0xB317127b50b22e62637E3c333A585a8ccfd0721D/events) showing emitted events of swaps created
![image](https://github.com/blockful-io/swaplace-subgraph/assets/102108966/733ea755-4f32-4d9e-a63b-e7b52a0aa515)

### Related issue:
[#886](https://github.com/ponder-sh/ponder/issues/886)

### Update

The number of events displayed in the log are showing correctly now (print 1), but still no return in the endpoint graphql(print2)

(print1)
![image](https://github.com/ponder-sh/ponder/assets/102108966/5b7b9459-871c-462d-8ba5-925269632258)

(print2)
![image](https://github.com/ponder-sh/ponder/assets/102108966/378a67ef-7d11-4864-8b68-427d2c064d91)

**Comment by swetshaw** [comment]
Hello @RafaDSan , I am from Kakarot team. Tried reproducing the issue using this [repo](https://github.com/blockful-io/swaplace-subgraph/tree/ponder). But able to get the events when using the same query with the graphql endpoint.

<img width="1061" alt="Screenshot 2024-08-07 at 2 57 28 PM" src="https://github.com/user-attachments/assets/e122b585-f660-4c35-9762-f5298d9f1996">

**Comment by RafaDSan** [comment]
Thank you for your time and feedback on this issue, @swetshaw! 
I'll close the issue as it's working correctly.
