### ISSUE TITLE
[Bug] Inconsistent missing events near tip of chain

### ISSUE THREAD

**Issue by spennyp** [ponder-sh/ponder#974]
My ponder app seems to be missing events within ~1 week from the tip of the chain. It's inconsistent, sometime it will work, and after some debugging I am able to make it work consistently with a few weird tweaks (changing start block, or commenting out other handlers).

Here is a minimal reproducible example:

```ts
// ponder.config.ts

export default createConfig({
  networks: {
    mainnet: { chainId: 1, transport: http(process.env.MAINNET_RPC_URL) },
    base: {
      chainId: base.id,
      transport: 
        rateLimit(http(process.env.BASE_RPC_URL), {
          requestsPerSecond: 12,
        }),
    },
  },
  contracts: {
    NounsToken: {
      abi: NounsTokenAbi,
      address: "0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03",
      network: "mainnet",
      startBlock: 12985438, // REF_A
    },
    NounsErc20Base: {
      abi: erc20Abi,
      address: "0x0a93a7BE7e7e426fC046e204C44d6b03A302b631",
      network: "base",
      startBlock: 17125047,
    },
  },
});
```

```ts
// ./src/handler.ts

ponder.on("NounsToken:Transfer", async ({ event, context }) => {
  console.log("DEBUG", event.args.tokenId);
});

// REF_B
ponder.on("NounsErc20Base:Transfer", async ({ event, context }) => {
  console.log("BASE TRANSFER");
});
```

With this configuration as is, the `NounsToken:Transfer` handler misses events from the past ~1 week.

But, I am able to make it pickup these events by making ANY of these changes:
* change to start block at `REF_A` to closer to the tip (ex `20303513`) 
* comment out the event handler below `REF_B`

Really strange behavior

**Comment by mchmatt** [comment]
Had the same happen to me this week, unfortunately I can't reproduce it after redeploying (created new DB and indexer instance, live swapped the old one)
I might be able to provide a DB dump (the one where the issue happened), if that's helpful let me know and I'll ask around

**Comment by mchmatt** [comment]
Are you able to reproduce this w/ 0.5.3? You might have been affected by https://github.com/ponder-sh/ponder/issues/999 like I did; 0.5.3 fixes that

**Comment by spennyp** [comment]
Sorry for the delay, yes this seems to have solved! Thanks
