### ISSUE TITLE
[feature] Support multiple addresses for factory contracts.

### ISSUE THREAD

**Issue by iherger** [ponder-sh/ponder#976]
Similar to multiple addresses for  standard contracts, see https://ponder.sh/docs/contracts-and-networks#multiple-addresses, would it be possible to have multiple addresses for factory contracts?

**Comment by 0xOlias** [comment]
Thanks for opening. Approximately how many factories do you anticipate including? Keep in mind that for this to make sense, all of the child contracts (across all factories) would need to have the same ABI.

**Comment by iherger** [comment]
Currently, we would need two different factory addresses.

This is related to issue #977 , i.e. to having multiple protocol deployments on the same chain. If multiple networks with the same chainId are supported, then we don't need multiple addresses for factory contracts, and the other way round.

**Comment by 0xOlias** [comment]
Got it. I think this issue highlights the fact that we still don't have an opinionated pattern for managing multiple environments (see https://github.com/ponder-sh/ponder/issues/768).

In your case, it seems like you want to index/serve data for both testnet and mainnet contracts in the same Ponder instance. I'd personally recommend against this, unless your app itself also displays data from test/prod at the same time.

Instead, consider using an environment variable to specify which environment the app should use, and return a different config accordingly. Here's an example of a config that does it this way: https://github.com/PleasrDAO/alleycat/blob/main/ponder.config.ts

**Comment by peterferguson** [comment]
An example of a factory that this would be useful is the [safe factory deployments](https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe_l2.json)

Same abi shared across factories with different address depending on the chain

**Comment by kyscott18** [comment]
This feature was released in v0.5.10
